"""
AI service with multi-tier routing.

Maps each action to one of three tiers:
  - Tier 1 (HYBRID): Local analytics provides verified facts to a cheap model.
  - Tier 2 (LIGHT): Cheap model (e.g. gpt-4o-mini) for simple recommendations.
  - Tier 3 (STRONG): More capable model for complex reasoning.

Usage:
    from src.ai_service import TaskRouter
    router = TaskRouter()
    sections = await router.route(action, parameters, context, db, user_id)
"""

import json
import logging
from typing import Any

from aiohttp import ClientTimeout, ContentTypeError

from src.ai_prompt import create_prompt
from src.ai_sections import _coerce_sections
from src.analytics import (
    get_fridge_status,
    get_nutrition_summary,
    get_spending_summary,
    suggest_recipes,
)
from src.config import (
    AI_API_KEY,
    AI_BASE_URL,
    AI_LIGHT_MODEL,
    AI_STRONG_MODEL,
    AI_TIMEOUT_SECONDS,
)
from src.integrations.http import get_http_session
from src.utils import normalize_date

logger = logging.getLogger(__name__)


class AiServiceError(Exception):
    """Raised when the AI API returns an error or cannot be reached."""

    def __init__(self, message: str, status_code: int = 500):
        self.message = message
        self.status_code = status_code
        super().__init__(self.message)


# ---------------------------------------------------------------------------
#  Tier constants
# ---------------------------------------------------------------------------
# Actions where locally calculated facts are retained in the response and used
# as grounded context for the recommendation generated by the light model.
HYBRID_ACTIONS = frozenset(
    {
        "overall-analysis",
        "expiring-products",
        "recipes",
        "ingredients",
    }
)

# Actions best served by a cheap, fast LLM.
LIGHT_ACTIONS = frozenset(
    {
        "save-money",
        "healthy-food",
        "habits",
        "shopping-cart",
    }
)

# Actions that benefit from a more capable LLM.
STRONG_ACTIONS = frozenset(
    {
        "diet",
        "ask",
    }
)

ALL_ACTIONS = HYBRID_ACTIONS | LIGHT_ACTIONS | STRONG_ACTIONS


# ---------------------------------------------------------------------------
#  Helpers
# ---------------------------------------------------------------------------


def _truncate(text: str, limit: int = 12000) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def _build_user_prompt(action: str, parameters: dict | None, context: dict) -> str:
    rendered = create_prompt(action, {"parameters": parameters or {}, "context": context})
    if rendered is not None:
        return _truncate(rendered, 12000)
    parts: list[str] = []
    parts.append(f"action={action}")
    if parameters:
        parts.append("parameters=" + json.dumps(parameters, ensure_ascii=True))
    parts.append("context=" + json.dumps(context, ensure_ascii=True, default=str))
    return _truncate("\n---\n".join(parts), 12000)


async def _call_llm(
    model: str, action: str, prompt: str, max_tokens: int = 500, temperature: float = 0.2
) -> str:
    """Call the OpenAI-compatible API and return the raw response text."""
    system_prompt = "\n".join(
        (
            "# Ты — helpful nutrition assistant.",
            "Отвечай **кратко** и **по делу**. Используй **только контекст пользователя**.",
            "Упоминай в конце какая информация может помочь ответить лучше в следующий раз.",
            "Возвращай только обычный Markdown без JSON, объектов, массивов и кодовых блоков.",
            "",
            "\n---\n",
        )
    )

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {AI_API_KEY}",
    }

    body = {
        "is_sync": True,
        "temperature": temperature,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": max_tokens,
    }

    url = AI_BASE_URL + model
    logger.info("Calling AI provider", extra={"provider": "ai", "action": action})

    timeout = ClientTimeout(total=AI_TIMEOUT_SECONDS)
    session = await get_http_session()
    async with session.post(url, json=body, headers=headers, timeout=timeout) as resp:
        if not resp.ok:
            logger.warning(
                "AI provider returned non-success",
                extra={"status_code": resp.status, "action": action},
            )
            raise AiServiceError(
                f"AI API returned {resp.status}",
                status_code=resp.status,
            )

        resp_data: dict[str, Any]
        try:
            resp_data = await resp.json()
        except (ContentTypeError, ValueError) as exc:
            raise AiServiceError("Failed to parse AI API response") from exc

        if resp_data.get("error"):
            logger.warning("AI provider returned an error", extra={"action": action})
            raise AiServiceError("AI API returned an error")

        try:
            return resp_data["response"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            pass

        logger.warning("AI provider response structure not recognized", extra={"action": action})

        raise AiServiceError("Unexpected AI API response structure")


# ---------------------------------------------------------------------------
#  Local fact builders
# ---------------------------------------------------------------------------


def _section_text(title: str, text: str) -> dict[str, Any]:
    return {"type": "text", "title": title, "text": text}


def _section_score(title: str, value: float, max_val: float) -> dict[str, Any]:
    return {"type": "score", "title": title, "value": value, "max": max_val}


def _section_list(title: str, items: list[str]) -> dict[str, Any]:
    return {"type": "list", "title": title, "items": items}


def _section_chart(
    title: str, labels: list[str], values: list[float], kind: str = "bar"
) -> dict[str, Any]:
    return {"type": "chart", "title": title, "labels": labels, "values": values, "kind": kind}


# ---------------------------------------------------------------------------
#  Hybrid action facts
# ---------------------------------------------------------------------------


async def _local_overall_analysis(db, user_id, period_from, period_to) -> list[dict[str, Any]]:
    # AsyncSession is not safe for concurrent task use; SQLite executes these sequentially.
    spending = await get_spending_summary(db, user_id, period_from, period_to)
    nutrition = await get_nutrition_summary(db, user_id, period_from, period_to)

    sections: list[dict[str, Any]] = []

    if spending["receipt_count"] > 0:
        sections.append(
            _section_text(
                "Сводка по тратам",
                f"Всего чеков: {spending['receipt_count']}\n"
                f"Средний чек: {spending['avg_receipt']} ₽\n"
                f"Потрачено всего: {spending['total_spent']} ₽",
            )
        )

        if spending["by_month"]:
            labels = [m["month"] for m in spending["by_month"]]
            values = [m["total"] for m in spending["by_month"]]
            sections.append(_section_chart("Траты по месяцам", labels, values))

        if spending["by_store"]:
            sections.append(
                _section_list(
                    "Траты по магазинам",
                    [f"{s['store']}: {s['total']} ₽" for s in spending["by_store"]],
                )
            )

    if nutrition["total_calories"] > 0:
        sections.append(
            _section_text(
                "КБЖУ",
                f"Калории: {nutrition['total_calories']} ккал\n"
                f"Белки: {nutrition['total_proteins']} г\n"
                f"Жиры: {nutrition['total_fats']} г\n"
                f"Углеводы: {nutrition['total_carbs']} г",
            )
        )
        if nutrition.get("by_tag"):
            sections.append(
                _section_list(
                    "По категориям",
                    [f"{t['tag']}: {t['calories']} ккал" for t in nutrition["by_tag"]],
                )
            )

    if not sections:
        sections.append(_section_text("Нет данных", "За выбранный период нет информации."))

    return sections


async def _local_expiring_products(
    db, user_id, period_from=None, period_to=None
) -> list[dict[str, Any]]:
    fridge = await get_fridge_status(db, user_id)
    if not fridge:
        return [_section_text("Холодильник", "Пока нет информации о продуктах.")]

    # Filter expiring — days_until_empty is small or already negative
    expiring = [
        p for p in fridge if p["days_until_empty"] is not None and p["days_until_empty"] <= 3
    ]
    ok = [p for p in fridge if p["days_until_empty"] is None or p["days_until_empty"] > 3]

    sections: list[dict[str, Any]] = []

    if expiring:
        sections.append(
            _section_list(
                "Скоро закончится",
                [
                    f"{p['product_name']} — осталось ~{p['estimated_quantity']} кг (~{p['days_until_empty']} дн.)"
                    for p in expiring
                ],
            )
        )

    if ok:
        sections.append(
            _section_list(
                "В наличии",
                [
                    f"{p['product_name']} — {p['estimated_quantity']} кг (до {p['expected_expiry']})"
                    for p in ok[:10]
                ],
            )
        )

    return sections


async def _local_recipes(db, user_id, period_from=None, period_to=None) -> list[dict[str, Any]]:
    suggestions = await suggest_recipes(db, user_id, limit=5)
    if not suggestions:
        return [_section_text("Рецепты", "Нет подходящих рецептов для ваших продуктов.")]

    sections: list[dict[str, Any]] = []
    for s in suggestions:
        recipe = s["recipe"]
        parts = [
            f"**{recipe['name']}** (совпадение: {s['match_score'] * 100:.0f}%)",
        ]
        if recipe.get("cooking_time_minutes"):
            parts.append(f"⏱ {recipe['cooking_time_minutes']} мин.")
        if s["missing_products"]:
            missing_names = [m["product_name"] for m in s["missing_products"]]
            parts.append(f"❌ Не хватает: {', '.join(missing_names)}")
        if s["available_substitutes"]:
            for sub in s["available_substitutes"]:
                parts.append(f"🔄 {sub['original_name']} → {sub['substitute_name']}")
        sections.append(_section_text(recipe["name"], "\n".join(parts)))

    return sections


async def _local_ingredients(db, user_id, period_from=None, period_to=None) -> list[dict[str, Any]]:
    nutrition = await get_nutrition_summary(db, user_id, period_from, period_to)
    if not nutrition or nutrition["total_calories"] == 0:
        return [_section_text("Состав продуктов", "Нет данных за выбранный период.")]

    sections: list[dict[str, Any]] = [
        _section_text(
            "Нутриенты за период",
            f"Калории: {nutrition['total_calories']} ккал\n"
            f"Белки: {nutrition['total_proteins']} г\n"
            f"Жиры: {nutrition['total_fats']} г\n"
            f"Углеводы: {nutrition['total_carbs']} г\n"
            f"Клетчатка: {nutrition.get('total_fiber', '—')} г\n"
            f"Сахар: {nutrition.get('total_sugar', '—')} г\n"
            f"Насыщенные жиры: {nutrition.get('total_saturated_fats', '—')} г\n"
            f"Натрий: {nutrition.get('total_sodium', '—')} мг",
        ),
    ]

    if nutrition.get("by_tag"):
        sections.append(
            _section_list(
                "По категориям",
                [
                    f"{t['tag']}: {t['calories']} ккал, {t['proteins']} г белков"
                    for t in nutrition["by_tag"]
                ],
            )
        )

    return sections


async def _build_local_facts(
    action: str,
    db: Any,
    user_id: str,
    period_from: Any,
    period_to: Any,
) -> list[dict[str, Any]]:
    """Return deterministic facts for a hybrid action before AI advice."""
    local_handlers = {
        "overall-analysis": _local_overall_analysis,
        "expiring-products": _local_expiring_products,
        "recipes": _local_recipes,
        "ingredients": _local_ingredients,
    }
    return await local_handlers[action](db, user_id, period_from, period_to)


# ---------------------------------------------------------------------------
#  Public interface
# ---------------------------------------------------------------------------


class TaskRouter:
    """
    Routes AI requests to the appropriate tier
    based on the action type.
    """

    async def route(
        self,
        action: str,
        parameters: dict[str, Any] | None,
        context: dict[str, Any],
        db=None,
        user_id: str | None = None,
        force_light: bool = False,
    ) -> list[dict[str, Any]]:
        """
        Returns a list of AiSection-compatible dicts.

        The caller (routers/ai.py) is responsible for:
          - loading receipts and building context
          - checking credits
          - caching
        """
        if action not in ALL_ACTIONS:
            return [_section_text("Ошибка", f"Неизвестное действие: {action}")]

        values = parameters or {}
        period_from = normalize_date(values["periodFrom"]) if values.get("periodFrom") else None
        period_to = normalize_date(values["periodTo"]) if values.get("periodTo") else None

        local_facts: list[dict[str, Any]] = []
        if action in HYBRID_ACTIONS:
            if not db or not user_id:
                return [_section_text("Ошибка", "Требуется аутентификация для анализа.")]
            local_facts = await _build_local_facts(
                action, db, user_id, period_from, period_to
            )
            context = {**context, "local_facts": local_facts}

        # ---- LLM calls ----
        if force_light or action in HYBRID_ACTIONS | LIGHT_ACTIONS:
            model = AI_LIGHT_MODEL
            max_tokens = 400
            temperature = 0.2
        else:  # STRONG_ACTIONS
            model = AI_STRONG_MODEL or AI_LIGHT_MODEL
            max_tokens = 800
            temperature = 0.3

        prompt = _build_user_prompt(action, parameters, context)
        raw = await _call_llm(model, action, prompt, max_tokens=max_tokens, temperature=temperature)
        advice_sections = _coerce_sections(raw)
        return local_facts + advice_sections


# ---------------------------------------------------------------------------
#  Backward-compatible top-level function
# ---------------------------------------------------------------------------


async def generate_ai_response(
    action: str,
    parameters: dict[str, Any] | None,
    context: dict[str, Any],
    db=None,
    user_id: str | None = None,
) -> str:
    """
    Legacy entry point — maintained for tests and potential external callers.

    Returns JSON-like text for hybrid and LLM tiers.
    Prefer using TaskRouter.route() directly for new code.
    """
    router = TaskRouter()
    sections = await router.route(action, parameters, context, db=db, user_id=user_id)
    return json.dumps(sections, ensure_ascii=False)
