"""remove unique constraint from Payment.user_id; add pending payment limit app check

Revision ID: 104d0685c008
Revises:
Create Date: 2026-07-18 00:00:43.196875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "104d0685c008"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_subcription_in_process_user_id"),
        "subcription_in_process",
        ["user_id"],
        unique=False,
    )
    op.drop_column("subscriptions", "platform")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("platform", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_subcription_in_process_user_id"), table_name="subcription_in_process")
    # ### end Alembic commands ###
