"""remove unique constraint from Payment.user_id; add pending payment limit app check

Revision ID: 104d0685c008
Revises:
Create Date: 2026-07-18 00:00:43.196875

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "104d0685c008"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_legacy_baseline() -> None:
    """Create the pre-Alembic schema for a new, empty database.

    This revision was introduced after the application had already been
    creating its schema at runtime.  Subsequent revisions intentionally
    transform that old schema, so a fresh database must begin with it too.
    """
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("premium", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("subscription_expires", sa.DateTime()),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_table(
        "email_codes_storage",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("store", sa.String()),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("receipt_expires_at", sa.DateTime()),
    )
    op.create_table(
        "receipt_items",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("receipt_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("product_id", sa.String()),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False, unique=True),
        sa.Column("purchase_token", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False, server_default="legacy"),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime()),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    for table_name, columns in {
        "devices": (
            sa.Column("id", sa.String(), primary_key=True),
            sa.Column("device_id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
        ),
        "ai_reports": (
            sa.Column("id", sa.String(), primary_key=True),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
        ),
        "subcription_in_process": (
            sa.Column("id", sa.String(), primary_key=True),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("status", sa.String(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
        ),
        "ai_cache": (
            sa.Column("id", sa.String(), primary_key=True),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("action", sa.String(), nullable=False),
            sa.Column("context_hash", sa.String(), nullable=False),
            sa.Column("question_hash", sa.String()),
            sa.Column("expires_at", sa.DateTime(), nullable=False),
        ),
    }.items():
        op.create_table(table_name, *columns)


def upgrade() -> None:
    """Upgrade schema."""
    table_names = set(sa.inspect(op.get_bind()).get_table_names()) - {"alembic_version"}
    if not table_names:
        _create_legacy_baseline()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_subcription_in_process_user_id"),
        "subcription_in_process",
        ["user_id"],
        unique=False,
    )
    op.drop_column("subscriptions", "platform")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("platform", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_subcription_in_process_user_id"), table_name="subcription_in_process")
    # ### end Alembic commands ###
